language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master

before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/jbboehr/libmustache.git libmustache
  - cd libmustache
  - autoreconf -i && ./configure && make && sudo make install
  - cd ..

script:
  - phpize
  - ./configure --enable-mustache
  - make
  - echo n | make test

