sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  include:
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: 'master'

branches:
  only:
    - master
    - travis
    - ci

addons:
  apt:
    packages:
      - lcov

before_install:
- travis_retry git submodule update --init --recursive
- source ./.ci/travis_php.sh
- before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
