sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  - language: nix
    env:
      - NIX_CHANNEL=unstable
      - NIX_PHP_ATTR=php
  include:
  - language: php
    php: '7.1'
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: 'master'
  - language: nix
    env:
    - NIX_CHANNEL=20.03
    - NIX_PHP_ATTR=php72
  - language: nix
    env:
    - NIX_CHANNEL=20.03
    - NIX_PHP_ATTR=php73
  - language: nix
    env:
    - NIX_CHANNEL=20.03
    - NIX_PHP_ATTR=php74
  - language: nix
    env:
    - NIX_CHANNEL=unstable
    - NIX_PHP_ATTR=php

env:
  global:
    - LIBMUSTACHE_VERSION: v0.5.0

branches:
  only:
    - master
    - travis
    - ci

cache: ccache

addons:
  apt:
    packages:
      - lcov

before_install:
- travis_retry git submodule update --init --recursive
- source ./.ci/travis_env.sh
- before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
